import 'package:configs/configs.dart';
import 'package:draftwing/ui/widgets/design/button/button.dart';
import 'package:draftwing/ui/widgets/design/modal/app_modal_base.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_form_builder/flutter_form_builder.dart';
import 'package:iconsax_flutter/iconsax_flutter.dart';
import 'package:intl/intl.dart';

// part 'email.dart';
// part 'utils.dart';
// part 'password.dart';
part '_base.dart';
part '_data.dart';
part '_enums.dart';
part '_model.dart';
// part '_provider.dart';
// part '_validator.dart';
// part 'radio/radio.dart';
// part 'radio/_options.dart';
// part 'country_picker.dart';
// part 'first_name.dart';
// part 'last_name.dart';
part 'autocomplete/_modal.dart';
// part 'details/country.dart';
// part 'details/gender.dart';
// part 'details/city.dart';
part 'select_input/select_input.dart';
// part 'phone_input/phone_input.dart';
// part 'checkbox/checkbox.dart';
part 'text_input/content.dart';
part 'text_input/text_input.dart';
// part 'pin_code/pin_code.dart';
part 'date_input/date_input.dart';
// part 'select_input/select_input.dart';
// part 'toggle/toggle.dart';
part 'chips_input/chips_input.dart';
