name: repos
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: 3.7.2

# Add regular dependencies here.
dependencies:
  # models generation
  json_annotation: 4.9.0
  freezed_annotation: 2.4.4

  # firebase
  firebase_vertexai: 1.6.0

  # cache
  hive: 2.2.3
  hive_flutter: 1.1.0

  # fault
  fault:
    path: ../fault

dev_dependencies:
  lints: 5.0.0

  freezed: 2.5.7
  build_runner: 2.4.13
  hive_generator: 2.0.1
  json_serializable: 6.8.0
