name: fault
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: 3.7.2

# Add regular dependencies here.
dependencies:
  # cache
  hive: 2.2.3
  hive_flutter: 1.1.0

dev_dependencies:
  lints: 5.0.0
