// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkD6EWqMVLB-aSnknwhlX8KNMrZZ3Igvs',
    appId: '1:733913963330:web:1c9f7025c5ecc472c706db',
    messagingSenderId: '733913963330',
    projectId: 'devxi-dev',
    authDomain: 'devxi-dev.firebaseapp.com',
    storageBucket: 'devxi-dev.firebasestorage.app',
    measurementId: 'G-404E52P49C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4URcJuVSLn4CdCYnvBYxzM-g9LuP7dK0',
    appId: '1:733913963330:android:3cd0c4a2c71738a1c706db',
    messagingSenderId: '733913963330',
    projectId: 'devxi-dev',
    storageBucket: 'devxi-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59KbXb5ya0rdVh8ZDc4vbcNwE8UaVcok',
    appId: '1:733913963330:ios:9ea5714a19f4690cc706db',
    messagingSenderId: '733913963330',
    projectId: 'devxi-dev',
    storageBucket: 'devxi-dev.firebasestorage.app',
    iosBundleId: 'com.hmz.draftwing',
  );
}
