name: brain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

# for melos to work
resolution: workspace

environment:
  sdk: 3.7.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # configs
  configs:
    path: ../configs

dev_dependencies:
  lints: 5.0.0
  test: 1.24.0
