name: brain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

# for melos to work
resolution: workspace

environment:
  sdk: 3.7.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter

  # configs
  configs:
    path: ../configs

  # network
  dio: 5.7.0
  alice:
    path: ../alice

  # notification
  flutter_local_notifications: 18.0.1

  # dotenv
  flutter_dotenv: 5.2.1

dev_dependencies:
  lints: 5.0.0

flutter:
  assets:
    - .env